import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.Properties;

public final class ReportIdentity {

    public final String studyTitle;
    public final String institution;
    public final String degree;
    public final String authors;
    public final String thesisAdviser;
    public final String reportFooterNote;

    private ReportIdentity(String studyTitle, String institution, String degree,
                           String authors, String thesisAdviser, String reportFooterNote) {
        this.studyTitle = studyTitle;
        this.institution = institution;
        this.degree = degree;
        this.authors = authors;
        this.thesisAdviser = thesisAdviser;
        this.reportFooterNote = reportFooterNote;
    }

    private static Path globalPath() {
        return Path.of(System.getProperty("user.home"),
                ".aoma-heritage-monitor", "report-identity.properties");
    }

    public static Path ensureGlobalDefault() throws IOException {
        Path p = globalPath();
        Files.createDirectories(p.getParent());
        if (!Files.exists(p)) {
            Files.writeString(p, defaultContent(), StandardCharsets.UTF_8);
        }
        return p;
    }

    public static Path ensurePerOutDir(Path outDir) throws IOException {
        Path global = ensureGlobalDefault();
        Path perDir = outDir.resolve("report-identity.properties");
        if (!Files.exists(perDir)) {
            Files.copy(global, perDir, StandardCopyOption.REPLACE_EXISTING);
        }
        return perDir;
    }

    public static ReportIdentity load(Path outDir) throws IOException {
        Path path = outDir.resolve("report-identity.properties");
        if (!Files.exists(path)) {
            path = ensureGlobalDefault();
        }
        Properties props = new Properties();
        try (BufferedReader r = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            props.load(r);
        }
        return new ReportIdentity(
                trim(props.getProperty("studyTitle",
                        "AOMA Heritage Structural Health Monitoring")),
                trim(props.getProperty("institution", "FEU Institute of Technology")),
                trim(props.getProperty("degree",
                        "Bachelor of Science in Civil Engineering")),
                trim(props.getProperty("authors", "")),
                trim(props.getProperty("thesisAdviser", "")),
                trim(props.getProperty("reportFooterNote",
                        "Generated by AOMA Heritage Monitor"))
        );
    }

    static String trim(String s) {
        return s == null ? "" : s.trim();
    }

    private static String defaultContent() {
        return "studyTitle=Designing and Implementation of Automated-OMA System to Monitor Safety and Serviceability of Heritage Buildings\n" +
               "institution=FEU Institute of Technology\n" +
               "degree=Bachelor of Science in Civil Engineering\n" +
               "authors=John Rafael Alejandrino\n" +
               "thesisAdviser=\n" +
               "reportFooterNote=Generated by AOMA Heritage Monitor - For Research Purposes Only\n";
    }
}
